spring:
  application:
    name: zuul-service

server:
  port: 80

management:
  endpoints:
    web:
      exposure:
        include: "*"
    default:
      web:
        enabled: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server.binarybutter.com/eureka
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${server.port}
  info:
    app:
      name: zuul-proxy